[".config/opencode"]
    type = "git-repo"
    url = "git@github.com:xnoto/opencode-config.git"
    pull.args = ["--ff-only"]

[".config/opencode-llama"]
    type = "git-repo"
    url = "git@github.com:xnoto/opencode-llama-config.git"
    pull.args = ["--ff-only"]

[".codex"]
    type = "git-repo"
    url = "git@github.com:xnoto/codex-config.git"
    pull.args = ["--ff-only"]

[".config/alacritty/alacritty-theme-linux-vconsole"]
    type = "git-repo"
    url = "git@github.com:xnoto/alacritty-theme-linux-vconsole.git"

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"

[".claude/settings.json"]
    type = "file"
    url = "https://raw.githubusercontent.com/xnoto/claude-config/main/settings.json"

[".claude/settings.local.json"]
    type = "file"
    url = "https://raw.githubusercontent.com/xnoto/claude-config/main/settings.local.json"
