set -gu @thm_strong_primary
set -gu @thm_primary
set -gu @thm_light_primary
set -gu @thm_secondary
set -gu @thm_prefix
set -gu @thm_fg
set -gu @thm_core
set -gu @thm_mantle
set -gu @thm_surface
set -gu @thm_visual
set -gu @thm_red
set -gu @thm_orange
set -gu @thm_yellow
set -gu @thm_green
set -gu @thm_teal
set -gu @thm_blue
set -gu @thm_indigo
