source-file ~/.config/tmux/oasis-reset.conf
set -g @oasis_flavor "dune_dark"
if-shell "test -e ~/.tmux/plugins/tmux-oasis/oasis_tmux.conf" \
     "source-file ~/.tmux/plugins/tmux-oasis/oasis_tmux.conf"
